apiVersion: v1
kind: Pod
metadata:
 name: front
 labels:
  env : prod
  app: main
  tier: frontend
  owner: alexey.ilin
spec:
 containers:
  - name: container-apache
#   image: httpd:latest
    image: nginx:latest
    ports:
    - containerPort: 80
